### ISSUE TITLE
TypeError : Cannot read property 'join' of null

### ISSUE THREAD

**Issue by guziks** [asciidoctor/asciidoctor-chrome-extension#32]
# My actions
1. install extention from webstore
2. check "Allow access to file URLs"
3. drag test.adoc (anything, even empty) to browser
# Result

page with content:

```
Error
TypeError : Cannot read property 'join' of null
```
# Versions

chrome 34.0.1847.131
asciidoctor-chrome-extension 0.3.0
windows 8.1

**Comment by stayfool** [comment]
This problem is still existed, error message:
```
TypeError: Cannot read property 'join' of null
    at Date.ːzone [as $zone] (chrome-extension://iaalpfgpbocpdfblpnhhgllgbdbchmia/js/vendor/asciidoctor.js:17868:62)
    at chrome-extension://iaalpfgpbocpdfblpnhhgllgbdbchmia/js/vendor/asciidoctor.js:18056:28
    at RegExp.[Symbol.replace] (<anonymous>)
    at String.replace (native)
    at Date.ːstrftime [as $strftime] (chrome-extension://iaalpfgpbocpdfblpnhhgllgbdbchmia/js/vendor/asciidoctor.js:17919:21)
    at $Document.ːinitialize [as $initialize] (chrome-extension://iaalpfgpbocpdfblpnhhgllgbdbchmia/js/vendor/asciidoctor.js:27367:58)
    at singleton_class_alloc.TMP_4 [as $new] (chrome-extension://iaalpfgpbocpdfblpnhhgllgbdbchmia/js/vendor/asciidoctor.js:3146:23)
    at module_constructor.ːload [as $load] (chrome-extension://iaalpfgpbocpdfblpnhhgllgbdbchmia/js/vendor/asciidoctor.js:33226:43)
    at module_constructor.Opal.Asciidoctor.$$class.$$proto.load (chrome-extension://iaalpfgpbocpdfblpnhhgllgbdbchmia/js/vendor/asciidoctor.js:33467:15)
    at updateBody (chrome-extension://iaalpfgpbocpdfblpnhhgllgbdbchmia/js/renderer.js:74:25)
```

**Version
window 10
chrome 56
asciidoctor.js 1.5.5.100

**Comment by Mogztter** [comment]
@stayfool Thanks for reporting.

The code in Opal is now:

```javascript
    Opal.defn(self, '$zone', TMP_27 = function ːzone() {
      var self = this;

      
      var string = self.toString(),
          result;

      if (string.indexOf('(') == -1) {
        result = string.match(/[A-Z]{3,4}/)[0];
      }
      else {
        result = string.match(/\([^)]+\)/)[0].match(/[A-Z]/g).join('');
      }

      if (result == "GMT" && /(GMT\W*\d{4})/.test(string)) {
        return RegExp.$1;
      }
      else {
        return result;
      }
    
    }, TMP_27.$$arity = 0);
```

In your case `string.match(/\([^)]+\)/)[0].match(/[A-Z]/g)` returns null.

I may have to submit my workaround to Opal to fix this issue.

**Comment by tequlia2pop** [comment]
The problem still exists and I have to roll back to use the previous version 1.5.4.111.:sweat_smile:

**Comment by Mogztter** [comment]
Thanks for sharing @tequlia2pop. Could you please confirm that you did have the same error message ? What is your locale ?

**Comment by Mogztter** [comment]
Ah! I think I found the issue.

The code in Ruby is:
```ruby
localtime = (attrs['localtime'] ||= begin
  now.strftime '%H:%M:%S %Z'
rescue # Asciidoctor.js fails if timezone string has characters outside basic Latin (see asciidoctor.js#23)
  now.strftime '%H:%M:%S %z'
end)
```
https://github.com/asciidoctor/asciidoctor/blob/5da225b5db5e2cf5132709075b1071e9e013a578/lib/asciidoctor/document.rb#L423-L427

And in JavaScript:

```javascript
try {
  localtime = (($writer = ["localtime", now.$strftime("%H:%M:%S %Z")]), $send(attrs, '[]=', Opal.to_a($writer)), $writer[$rb_minus($writer["length"], 1)])
} catch ($err) {
  if (Opal.rescue($err, [Opal.const_get($scopes, 'StandardError', true, true)])) {
    try {
      localtime = (($writer = ["localtime", now.$strftime("%H:%M:%S %z")]), $send(attrs, '[]=', Opal.to_a($writer)), $writer[$rb_minus($writer["length"], 1)])
    } finally { Opal.pop_exception() }
  } else { throw $err; }
};
```

@mojavelinux As far as I understand, `TypeError` is not a "StandardError" and thus the exception is thrown...

**Comment by Mogztter** [comment]
Here's a quick way to reproduce this issue with Opal:

.test.rb
```ruby
now = ::Time.now
begin
  now.strftime '%H:%M:%S %Z'
rescue
  now.strftime '%H:%M:%S %z'
end
```

```
bundle exec opal -- test.rb
```

```
TZ="/usr/share/zoneinfo/oops" bundle exec opal -- test.rb
```
```
TypeError: Cannot read property '0' of null
    at Date.$$zone [as $zone] (/tmp/opal-nodejs-runner-20170604-15468-mw69b9:19305:43)
    at /tmp/opal-nodejs-runner-20170604-15468-mw69b9:19491:28
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at Date.$$strftime [as $strftime] (/tmp/opal-nodejs-runner-20170604-15468-mw69b9:19354:21)
    at /tmp/opal-nodejs-runner-20170604-15468-mw69b9:21159:16
    at Object.<anonymous> (/tmp/opal-nodejs-runner-20170604-15468-mw69b9:21167:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

If the timezone is unknown the date will be something like: `Sun Jun 04 2017 08:34:00 GMT+0000 ()`

**Comment by Mogztter** [comment]
The following is working:
```ruby
now = ::Time.now
begin
  now.strftime '%H:%M:%S %Z'
rescue Exception
  now.strftime '%H:%M:%S %z'
end
```

**Comment by Mogztter** [comment]
I think JavaScript's TypeError should be "map" as Ruby's TypeError.
I've opened an issue on Opal: https://github.com/opal/opal/issues/1675

**Comment by noah538** [comment]
>>@Mogztter the root cause should be fixed by b7701da and caaa3a2 😉
Can you kindly tell me how to apply 'opal patch' to fix "TypeError : Cannot read property 'join' of null" happens in asciidoctor-chrome-extension, thank you.

**Comment by Mogztter** [comment]
@noah538 What version of `asciidoctor-chrome-extension` are you using ?

**Comment by noah538** [comment]
My version was direct download the master from github.com ( by 8/23): 
Asciidoctor.js Live Preview 1.5.5.101
Render AsciiDoc (.ad, .adoc, .asc, .asciidoc) as HTML inside your browser!
ID： dmhmaknbgaldhckmdgjfnhbihlenhomn
Source： F:\asciidoctor-chrome-extension-master\app

for a simple asciidoc:
= aaa
== bbb
=== ccc

I still have  error:

renderer.js:62 TypeError: Cannot read property 'join' of null
    at Date.ːzone [as $zone] (asciidoctor.js:17868)
    at asciidoctor.js:18056
    at RegExp.[Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at Date.ːstrftime [as $strftime] (asciidoctor.js:17919)
    at $Document.ːinitialize [as $initialize] (asciidoctor.js:27367)
    at singleton_class_alloc.TMP_4 [as $new] (asciidoctor.js:3146)
    at module_constructor.ːload [as $load] (asciidoctor.js:33226)
    at module_constructor.Opal.Asciidoctor.$$class.$$proto.load (asciidoctor.js:33467)
    at updateBody (renderer.js:72)

should I patch some changelist? thank you.

**Comment by Mogztter** [comment]
> should I patch some changelist? 

@noah538 No, this issue will be fixed once https://github.com/asciidoctor/asciidoctor-chrome-extension/issues/161 is resolved. But I want to fix https://github.com/asciidoctor/asciidoctor.js/issues/367 first so we can make a Asciidoctor.js 1.5.6 "final" version.

Sorry about that, hopefully a new release of the Chrome extension will be available in the next couple of weeks.

**Comment by Mogztter** [comment]
Having said that, I think you can monkey-patch the extension if you are using master.

In `app/js/vendor/asciidoctor.js` (line 17868):

```diff
-result = string.match(/\([^)]+\)/)[0].match(/[A-Z]/g).join('');
+result = string.match(/\((.+)\)(?:\s|$)/)[1];
```

@noah538 Let me know if it's working :wink:

**Comment by noah538** [comment]
@Mogztter  It works like a charm!! 👍  Thank you! 💯
